services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    network_mode: "container:ai-net"
    volumes:
      - ollama_gpu_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  ollama_gpu_data: {}
