services:
  vllm:
    image: vllm/vllm-openai
    container_name: vllm
    restart: unless-stopped
    network_mode: "container:ai-net"
    command: --model HuggingFaceAdı/ModelAdı --host 0.0.0.0 --port 8000
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  huggingface_cache: {}
